### ISSUE TITLE
Extension Freezes gnome-shell

### ISSUE THREAD

**Issue by JavierRizzoA** [N-Yuki/gnome-shell-extension-workspace-isolated-dash#4]
On gnome 3.16, when the extension is enabled, gnome-shell randomly consumes 100% of CPU every few minutes (or even less), resulting on a freeze that lasts some seconds.

**Comment by N-Yuki** [comment]
Thanks for reporting this. Can you provide the exact version number (ie. 3.16.x) and a list of other extensions that are enabled?

**Comment by JavierRizzoA** [comment]
Yes. I'm running 3.16.2 on Arch Linux. I was only using Alternatetab, Drop down terminal, and Media Player indicator; but also tried Workspace isolated dash alone, and the problem persisted.

**Comment by N-Yuki** [comment]
I need someone to confirm this issue to try find what the common thing is since I can't reproduce it, and I can't imagine this extension alone causing 100% CPU usage.

**Comment by mdillavou** [comment]
I also have this issue. It seems to happen when I get a new notification.

**Comment by N-Yuki** [comment]
Okay, thanks for the extra info. I'll see how notifications work when I get some time to see how it interacts with my stuff.

**Comment by N-Yuki** [comment]
Okay, so I finally got around to looking into this problem, and I have an idea. Do people who get affected by this have a /lot/ of installed software?
Also, I pushed out an update for 3.16 and above, which might lessen the CPU usage a bit now.

**Comment by mdillavou** [comment]
This does not appear to fix the freezing for me. I do not have a lot of apps installed (4 pages in overview, so < 90)

**Comment by franglais125** [comment]
Could this be related to tracker? In a way, it could act in the same way as having a lot of apps installed.

I used to have this problem, but not anymore since I cleaned the cache for tracker and deactivated it completely. Or maybe it was just a coincidence that I stopped seeing this.

I'm running Gnome 3.14 on Debian Stable. As others reported, I tried disabling all other extensions to find the culprit.

**Comment by N-Yuki** [comment]
I haven't been able to reproduce this issue yet, but I'm guessing that it's happening when it's refreshing the state of all the running apps, and I tell the shell that the set of installed applications might have changed.

Does tracker monitor the list of installed applications too?

I guess one idea to test would be installing/uninstalling an application, and see if that also triggers a freeze.

**Comment by franglais125** [comment]
I don't know if tracker monitors applications as well. Also, as I said, it could just be a coincidence!

I've seen gnome-shell increase the use of RAM when installing an application, but I don't know if that's due to tracker, and if it is, what's the exact impact.

Sorry I can't be more helpful. This issue is a bit hard to pinpoint.

In any case, to me (from my experience) this seems to be the same as https://github.com/N-Yuki/gnome-shell-extension-workspace-isolated-dash/issues/7. Perhaps when the Shell has to perform a given task (like show a notification), since it is using so much RAM, it has to parse it/move it around/whatever, and it takes quite a few CPU cycles, hence the freezing.

@mdillavou or @JavierRizzoA do you know if gnome-shell is using a lot of RAM when you get the freezing problem? I'm not affected by either issue anymore (even after running the same session for days) so I can't really help!

Cheers, and thanks @N-Yuki for looking into this!

**Comment by JavierRizzoA** [comment]
I no longer have the problem, for some reason (maybe an update, or that I reinstalled my OS, or some other thing). But had a similar problem with Tracker (used 100% of CPU, causing a freeze), so I deactivated it. I'm now running Workspace Isolated Dash without any problem.

**Comment by mdillavou** [comment]
I have 23Gigs of RAM with usually 10+ at any given time, so I don't think that is the issue.

**Comment by franglais125** [comment]
Indeed, I have lots of free RAM too, but I don't think that that's the issue.

If gnome-shell is using a lot of RAM, it indicates that somewhere there is a problem with memory management (or object management, etc). The process itself has a lot of RAM to deal with.

As an example (just making this up), suppose gnome-shell duplicates the entries of the overview over and over again. This takes up a lot of RAM. Even if there is free RAM, at some point in needs to sort/deduplicate/whatever all these objetcs, which may cause a UI freeze for a few seconds.

@mdillavou do you still get the freezes from time to time? And if you do, when that happens, how much RAM is gnome-shell taking?

**Comment by mdillavou** [comment]
I have recently updated to fedora 24 and gnome-shell 3.20.2 and I still get the freezes when I get notifications. It doesn't happen on all notifications, maybe about 25% of the time, but the freeze is always associated with a gnome shell notification.

**Comment by franglais125** [comment]
I had better performance with Gnome 3.20 myself.

And, again, how much RAM is the "gnome-shell" process using when the freezes start?

**Comment by mdillavou** [comment]
I just had a freeze. gnome-shell is using 3.7%, or about 882M of my 23G, of which only 6.6G is in use, ~11G is cached, and ~6G is free. I am not currently using any swap.

**Comment by franglais125** [comment]
Hmm, 882M sounds like quite a bit for me... I don't claim that this is the source of the problem, but that's roughly the threshold when I started to have freezes.

In my case, gnome-shell would then progressively use more and more RAM, and at some point the session was essentially useless.

If you restart the session (Alt+F2 and then 'r'), do the freezes go away for a while? Say, until the RAM usage is large enough?
Or are the freezes present as soon as you log in?

For instance, I had no freezes (with a RAM usage of ~150MB). Opening the overview and browsing the apps (or installing a new app too) used to increase the memory usage quite fast for me (~400MB). And when the RAM usage got to ~800M I would get the freezes.

Again, I don't claim that this is the source of the problem, but just an observation...

**Comment by mdillavou** [comment]
I will monitor and report back if I notice anything specific.

**Comment by mdillavou** [comment]
I have experienced this within a few minutes of restarting gnome-shell, so I don't believe RAM usage is the problem. I also experience this even when this is the only extension enabled.

**Comment by franglais125** [comment]
Sorry, one more thing, I don't mean to spam.

@mdillavou A new version of this extension was released. Did you update it? And, if you did, do you still get random freezes?

https://extensions.gnome.org/extension/887/workspace-isolated-dash/

**Comment by N-Yuki** [comment]
Can anyone confirm that this is still an issue?

**Comment by mdillavou** [comment]
I have just updated. I will watch over the next few days and report back.

**Comment by N-Yuki** [comment]
@mdillavou any update on this?

**Comment by mdillavou** [comment]
I have not experienced this issue since the update, so I believe everything is working now.

**Comment by N-Yuki** [comment]
Okay, thanks. Will close this then.
